package models

import "time"

type UrlInfo struct {
	Id          int       `json:"id" gorm:"primaryKey"`
	Url         string    `json:"url" binding:"required"`
	ShortCode   string    `json:"shortCode"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	AccessCount int       `json:"accessCount"`
}

const Schema = `
CREATE TABLE url_info( 
    id int not null generated by default as identity(increment by 1 start 1 
    minvalue 1 maxvalue 2147483647 cache 1),
    url varchar(2000) not null,
    short_code varchar(255) not null,
    access_count int,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY(id)
);
`
