services:
  url-service:
    image: logeshwarann/url-shortener:2007.0835
    ports:
      - 8080:8080
    environment:
      - SERVER_HOST=
      - SERVER_PORT=8080
      - DB_USER=admin
      - DB_PWD=admin@123
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=url_db
      - DB_SSL_MODE=disable
      - TIME_ZONE=Asia/Shanghai
    depends_on:
      - postgres-db
  
  postgres-db:
    image: postgres:14-alpine  
    ports:
      - 5432:5432
    volumes:
      - .\data\:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_USER=admin
      - POSTGRES_DB=url_db
